export { default as AboutUs } from './aboutUs/AboutUs'
export { default as Address } from './address/Address'
export { default as Brands} from './brands/Brands'
export { default as Commodities } from './commodities/Commodities'
export { default as Contact } from './contact/Contact'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Menu } from './menu/Menu'
export { default as Products } from './products/Products'
export { default as Services } from './services/Services'
export { default as Slider } from './slider/Slider'
export { default as Tyres } from './tyres/Tyres'
export { default as Wapp } from './wapp/Wapp'